name: carry_devtools_extension
description: DevTools extension for debugging Carry sync state.
version: 0.1.0
repository: https://github.com/vsevex/carry/carry

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  carry:
    path: ../carry

flutter:
  uses-material-design: true
